# Project Euler
# Problem - 2
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# The first two terms of fibonacci sequence will be 1 and 2.

a = 1
b = 2
c = a + b
s = b

while c < 4000000 :
    if (c % 2 == 0) :
        s = s + c
    a = b
    b = c
    c = a + b
print s
